site_name: CitCom.ai - VRAIN
site_url: https://citcom-vrain.github.io
repo_url: https://github.com/CitCom-VRAIN/CitCom-VRAIN.github.io
repo_name: CitCom-VRAIN/CitCom-VRAIN.github.io
copyright: Copyright &copy; 2023 - 2024 CitCom.ai - VRAIN
site_dir: public
extra_css:
  - stylesheets/extra.css
theme:
  custom_dir: docs/overrides
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.copy
    - navigation.sections
    - navigation.footer
    - navigation.instant
    - navigation.indexes
  palette:
    - primary: custom
nav:
  - welcome.md
  - Getting started:
      - getting_started/index.md
      - Data Catalog: getting_started/data_catalog/index.md
      - Smart City Infrastructure: getting_started/smart_city_infra/index.md
      - Join a Data Space: getting_started/connect_to_dataspace/index.md
      - Data Space Deployment: getting_started/dataspace_deployment/index.md
  - Documentation:
      - documentation/index.md
      - Lepus: documentation/lepus.md
      - NGSI-V2 Broker to NGSI-LD via FIWARE IoT-Agent: documentation/iot_agent.md
      - Data Space:
          - documentation/data_space/index.md
          - Connectors:
              - documentation/data_space/connector/index.md
              - Eclipse: documentation/data_space/connector/eclipse_mvd.md
              - Fiware:
                  - documentation/data_space/connector/fiware/index.md
                  - AWS deployment: documentation/data_space/connector/fiware/aws_deployment.md
                  - Local deployment: documentation/data_space/connector/fiware/local_deployment.md
          - FIWARE Ecosystem:
              - documentation/data_space/fiware_ecosystem/index.md
              - Minimum Viable Data Space Infrastructure (MVDS-IaaS):
                  - documentation/data_space/fiware_ecosystem/mvds_iaas/index.md
  - AI services:
      - services/index.md
      - Minimal Interoperable AI Service: services/waste_collection.md
  - TEF Nodes:
      - tef/index.md
      - TEF sites analysis: tef/tef_list.md
  - Toolbox:
      - toolbox/index.md
      - AI Toolkit: toolbox/ai_toolkit.md
      - MIMs Toolkit: toolbox/mims_toolkit.md
      - Other Tools: toolbox/other_toolkit.md
  - FAQS:
      - faqs/index.md
extra:
  generator: false
markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
plugins:
  - search
  - git-revision-date-localized
