site_name: CitCom VRAIN 
site_url: https://citcom-vrain.github.io
repo_url: https://github.com/CitCom-VRAIN/CitCom-VRAIN.github.io
repo_name: CitCom-VRAIN/CitCom-VRAIN.github.io
copyright: Copyright &copy; 2023 - 2024 CitCom.ai - VRAIN
site_dir: public
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.copy
    - navigation.sections
    - navigation.footer
  palette: 
  - primary: black
extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/orgs/CitCom-VRAIN/repositories
    name: GitHub
  - icon: material/email
    link: mailto:<joamoteo@upv.es>
    name: Email 

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
plugins:
  - search
  - git-revision-date-localized